openapi: 3.0.0
info:
  title: API de autenticacao
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
paths:
  /login:
    post:
      tags:
        - default
      summary: POST Login
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logout:
    get:
      tags:
        - default
      summary: GET Logout
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user:
    post:
      tags:
        - default
      summary: POST User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Arthur
                password: admin
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/1:
    get:
      tags:
        - default
      summary: GET read User
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user/3:
    put:
      tags:
        - default
      summary: PUT update user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                password: ArtCat22
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DELETE user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}